name: Challenger Student
favicon: null
layout_spectrum: 0.78515
typography_spectrum: 0.61489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5380ff'
    - '#d90000'
    - '#00ccff'
  brandStrength: 1
  lightness: 0.0943677022587508
  saturation: 0.5248351062182337
  rhythmicContrast: 0.17271658265963197
purpose: []
